# Generated by Django 3.2 on 2021-07-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=200)),
                ('gender', models.TextField(max_length=100)),
                ('weight_status', models.TextField(max_length=100)),
                ('health_condition', models.TextField(max_length=100)),
                ('special_diet', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Note_ex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.CharField(max_length=200)),
                ('day', models.TextField(max_length=100)),
                ('food_category', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='note_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.TextField(max_length=200)),
                ('reference_name', models.TextField(max_length=100)),
                ('image_link', models.CharField(max_length=200)),
            ],
        ),
    ]
