# Generated by Django 3.2 on 2021-07-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=200)),
                ('dreference_name', models.TextField(max_length=100)),
                ('image_link', models.CharField(max_length=200)),
            ],
        ),
    ]
