# Generated by Django 3.2 on 2021-07-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_dreference_name_note_image_reference_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note_image',
            name='menu',
            field=models.TextField(max_length=200),
        ),
    ]
