# Generated by Django 3.2 on 2021-07-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_note_image_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note_image',
            name='image_link',
            field=models.TextField(max_length=100),
        ),
    ]
