# Generated by Django 3.2 on 2021-07-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_note_image_image_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='note_image_for_hroku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.TextField(max_length=200)),
                ('reference_name', models.TextField(max_length=100)),
                ('image_link', models.TextField(max_length=100)),
            ],
        ),
    ]
