# Generated by Django 3.2 on 2021-07-21 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_note_image_for_hroku'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note_image',
            new_name='note_images',
        ),
    ]
