# Generated by Django 3.2 on 2021-07-21 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_note_image_note_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='note_images',
            new_name='note_image',
        ),
    ]
